// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnrohzlbudpcufeiunlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxucm9oemxidWRwY3VmZWl1bmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzMzOTIsImV4cCI6MjA2NTgwOTM5Mn0.k18q3XiX8rzAFQCvWrviWo4C5bUgpcIg4Kv-zizlS2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);